[project]
name = "pydiscodb"  # another project is using DiscoDB name
version = "0.9.5"
description = "An efficient, immutable, persistent mapping object."
requires-python = ">=3.9"
dependencies = []
authors = [
    {name='Nokia Research Center'}
]
maintainers = [
    {name="Dan Bauman"}
]

[tool.setuptools.packages.find]
where = ["python", "src"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel.linux]
# This command runs for the manylinux containers (based on CentOS).
before-all = "dnf install -y check && rpm -ivh https://rpms.remirepo.net/enterprise/8/remi/x86_64/cmph-2.0-2.el8.remi.x86_64.rpm && rpm -ivh http://rpms.remirepo.net/enterprise/8/remi/x86_64/cmph-devel-2.0-2.el8.remi.x86_64.rpm"
archs = ["x86_64"]


[tool.cibuildwheel.macos]
before-all = "brew install libcmph"
archs = ["x86_64", "universal2", "arm64"]


[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
# This command runs for the musllinux containers (based on Alpine Linux).
before-all = "apk update && apk add libcmph cmph-dev"
archs = ["x86_64"]
